### ISSUE TITLE
Create page for each person

### ISSUE THREAD

**Issue by agarrharr** [agarrharr/orbit.fm#8]
It should have their name, description, and links, and then list all episodes they've been in as a host or guest across all the podcasts (shows) on the site.

**Comment by knittingcodemonkey** [comment]
Does this include guests? Are we linking every reference to us, from the show notes to this page?

**Comment by agarrharr** [comment]
It includes guests (probably). I'm not sure if **every** reference to us will link to this page, but probably.

**Comment by agarrharr** [comment]
For whoever picks this up, this will be done similar to how the podcast page and the episode page was made. See `gatsby-node.js` and `src/templates/` for an example.
